doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
        logging: '%kernel.debug%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Issues:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Issues'
                prefix: 'App\Issues'
                alias: Issues
            Security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Security'
                prefix: 'App\Security'
                alias: Security
